x = Msgbox("YOUR PC HAS BEEN HACKED",48,"WARNING!!!")
X = Msgbox("Your computer has been infected by a virus",48,"WARNING")
Y = Msgbox("Virus has infected the hard drive (C:). Deletion of the virus will require complete formatting of the hard drive (C:). Would you like to format hard drive? (C:)",4+48,"WARNING")
z = Msgbox("To avoid deletion of files, please kindly answer these questions")
h = Msgbox("will....",32,"<3")
a = Msgbox("you be....",32,"<3")
b = Msgbox("my valentine? ^-^",4+16,"<3")
b = Msgbox("Thank you for answering >-<")